#!/bin/sh

xinitrc=$HOME/.xinitrc

if [ -f $xinitrc ]; then
    $xinitrc
fi

for file in $HOME/.config/environment.d/*.conf; do
    if [ -f "$file" ]; then
	set -a
	. "$file"
	set +a
    fi
done

exec dwm
